config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'http_status_codes#index'
  resources :http_status_codes, only: %i[show index] do
    resources :haikus
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/haiku.rb
# frozen_string_literal: true

class Haiku < ApplicationRecord
  belongs_to :http_status_code
  belongs_to :writer
end

app/models/http_status_code.rb
# frozen_string_literal: true

class HttpStatusCode < ApplicationRecord
  has_many :haikus

  validates :description, :name, :category, presence: true
  validates :code, inclusion: { in: HttpStatusCodeConstants::CODES }
end

app/models/writer.rb
# frozen_string_literal: true

class Writer < ApplicationRecord
  has_many :haikus
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/haikus_controller.rb
class HaikusController < ApplicationController
  def index
    @http_status_code = HttpStatusCode.find(params[:http_status_code_id])
    @haikus = @http_status_code.haikus
  end

  def new
    @http_status_code = HttpStatusCode.find(params[:http_status_code_id])
    @haiku = Haiku.new
  end

  def create
    @http_status_code = HttpStatusCode.find(params[:http_status_code_id])
    @haiku = @http_status_code.haikus.new(haiku_params)

    if @haiku.save
      redirect_to http_status_code_haikus_path(@http_status_code),
                  notice: "Thanks for your haiku, I'm sure it was written with care, Be sure to review"
    else
      render :new
    end
  end

  private

  def haiku_params
    params.require(:haiku).permit(:title, :line1, :line2, :line3)
  end
end

app/controllers/http_status_codes_controller.rb
# frozen_string_literal: true

class HttpStatusCodesController < ApplicationController
  def index
    @http_status_codes = HttpStatusCode.all
  end

  def show
    @http_status_code = HttpStatusCode.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/haikus_helper.rb
module HaikusHelper
end

app/helpers/http_status_codes_helper.rb
# frozen_string_literal: true

module HttpStatusCodesHelper
end

app/views/haikus/index.html.erb
<h1>Haikus for <%= link_to @http_status_code.name, http_status_code_path(@http_status_code) %></h1>
<ul>
  <% @haikus.each do |haiku| %>
  <li>
    <%= haiku.title %>
    <%= haiku.line1 %>
    <%= haiku.line2 %>
    <%= haiku.line3 %>
  </li>
  <% end %>
</ul>

app/views/haikus/new.html.erb
<h1>Write a haiku for <%= link_to @http_status_code.name, @http_status_code %></h1>
<%= form_with(model: [@http_status_code, @haiku], local: true) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :line1 %>
  <%= f.text_field :line1 %>

  <%= f.label :line2 %>
  <%= f.text_field :line2 %>

  <%= f.label :line3 %>
  <%= f.text_field :line3 %>

  <%= f.submit %>
<% end %>

app/views/http_status_codes/index.html.erb
<ul>
  <% @http_status_codes.each do |http_status| %>
    <li><%= link_to http_status.code, http_status %></li>
  <% end %>
</ul>

app/views/http_status_codes/show.html.erb
<section class="http-status-code-details">
  <div>
    <h1><%= @http_status_code.code %></h1>
  </div>

  <aside>
    <h4>More Haikus</h4>
    <%= link_to "Write a http haiku", new_http_status_code_haiku_path(@http_status_code) %>
    <%= link_to "Read all of the http haikus for #{@http_status_code.code}", http_status_code_haikus_path(@http_status_code) %>
  </aside>
</section>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Made by <a href="http://www.andrew-schutt.com">Andrew Schutt</a>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to "HTTP Haiku", root_path %>
    <ul class="left">
    </ul>
    <ul class="right">
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Http Haiku</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="content">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>